[package]
name = "hacktable"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = "0.8.7"
faker_rand = "0.1.1"
rand = "0.8.5"
serde = { version = "1.0.228", features = ["derive"] }
surrealdb = "2.4.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
